name: Deploy Next.js App from GitHub to Contabo VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: '.'
          target: '/home/frontend/ebk-front'

      - name: Run commands on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/frontend
            chown -R root:root ./ebk-front
            cd ebk-front
            nvm install 18.19.0
            nvm use 18.19.0
            node -v
            npm -v
            # npm i
            # pm2 delete frontend
            # npm run build
            # pm2 start npm --name frontend -- start

      - name: Deployed!
        run: echo App deployed to Contabo VPS
